version: "3"
services:
  server:
    build: ./server
    container_name: orl-server
    user: "${USER_UID}"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/logs:ro
  logger:
    build: ./logger
    container_name: orl-logger
    user: "${USER_UID}"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./package/var/overrustlelogs:/logger:ro
      - ./logs:/logs
  frontend:
    image: nginx:latest
    container_name: orl-web
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - ./package/overrustlelogs.net.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./server/assets:/var/overrustlelogs/public/assets/:ro