logHost = "http://overrustlelogs.net"
maxOpenLogs = 1000

[destinygg]
logHost = "https://logs.destiny.gg"
socketURL = "wss://chat.destiny.gg/ws"
originURL = "https://www.destiny.gg"
cookie = ""

[twitch]
logHost = "https://ttv.overrustlelogs.net"
socketURL = "wss://irc-ws.chat.twitch.tv:443"
originURL = "http://irc-ws.twitch.tv"
clientID = ""
nick = ""
oauth = ""
admins = ["dbc__", "tensei_c"]
commandChannel = "overrustlelogs"